num1 =int(input("Enter first number"))
num2 =int(input("Enter second number"))
print("Addition of 2 numbers ",num1+num2)
print("Subtraction of 2 numbers ",num1-num2)
print("Multiplication of 2 numbers ",num1*num2)
print("Division of 2 numbers ",num1/num2)
print("Floor Divisin of 2 numbers ",num1//num2)
print("Modulus of 2 numbers ",num1%num2)
print("Exponent of 2 numbers ",num1**num2)