print("Hello, world")
print("My name is Alex. ")
print("I love playing soccer")
print("The result of 3 + 5 is:", 3 + 5)
print("Welcome to the world of programming")
print(4)
print("Hello Python \n")
print("hello ,5")
print("welcome to", end= "x")

